### ISSUE TITLE
Question on data curvature, K3

### ISSUE THREAD

**Issue by zunzun** [rhenanbartels/fit-example#1]
If the data is broken into multiple segments, each segment with its own unique K1 and K2, but all segments sharing the same K3 parameter, would that give you the information you need? I have tried a 50/50 upper/lower split based on M, and while it is fitting better than an all-data single region, more data segments will produce an overall better fit.

In a separate matter, I am becoming suspicious that the "wave component" is an artifact introduced by the equipment.

**Comment by rhenanbartels** [comment]
Hi James, I am not 100% sure if we split the curve the interpretation of the coefficients will be the same. On the other hand, in this specific type of disease that my group is studying the region of interest is on the left-most portion of the curve, something near 100/150 g.  So maybe, if the fitting returns to me a coefficient which tells me how fast the curve grows in this initial region could be a good first step. 
And going further, physiologically,  the disease in this case (lung emphysema) is known to be biphasic: it affects both portions of the curve (initial portion and final portion) in different ways.  So indeed, dividing the curve into two halves can bring information about the behavior in each phase of the disease.

Nevertheless, I've divided the curve into two curves using the x-axis (mass) in the half, but I'm still getting a bad fitting. Am I doing something wrong?

Do you have any suggestion of another equation that could fit the entire curve better and also gives me the "time constant"? Or an equation that has a better result on the beginning of the curve (last figure attached). I've considered using a biexponential curve: 
K1*exp(-K2*xdata) + K3*exp(-K4*xdata), but I am having a bad time trying to find the best initial guesses, any tips?

I've fitted the curve in the third image with a * pow(X, b), but I don't know yet how these coefficients can be useful in my case.

By the way, what is this "wave component"?

Thank you very much for you help.

**First Half**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/2186646/61166802-32ad8780-a50a-11e9-83e2-04df4725d674.png">

**Second Half**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/2186646/61166810-55d83700-a50a-11e9-89ad-85fe08b8b380.png">

**Initial Portion**
<img width="587" alt="image" src="https://user-images.githubusercontent.com/2186646/61166907-62f62580-a50c-11e9-8ab7-79045dc8fed8.png">

**Comment by zunzun** [comment]
You can email me directly using zunzun@zunzun.com for code questions or discussions. I am glad to help.

James
